/* mkstemp is POSIX, and -std=c17 asks for strict ISO C, which hides it. Must
 * come before any include that pulls in features.h. */
#define _POSIX_C_SOURCE 200809L

#include <check.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "suites.h"
#include "vorbis_decoder.h"

/*
 * Tests for vorbis_decoder.c: does miniaudio actually read an ogg once our
 * backend is registered, through both of the two entry points it can use.
 *
 * This is the one part of the audio stack that parses bytes the engine did not
 * produce, so the malformed cases below matter as much as the working one, and
 * the whole file is worth running under the sanitizers.
 *
 * The fixture is generated by tools/make_ogg_fixture.c and committed:
 * a quarter second of stereo, 440 Hz left and 880 Hz right. It is deliberately
 * asymmetric so that a decoder which drops a channel, or collapses to mono, is
 * visible rather than merely quieter. Paths are relative to the repository
 * root, which is where `make test` runs from.
 */

#define FIXTURE "spec_core/fixtures/tone.ogg"
#define FIXTURE_CHANNELS 2
#define FIXTURE_RATE 44100
#define FIXTURE_FRAMES 11025 /* 0.25 s */

/* A decoder config with our vorbis backend registered — the one line of wiring
 * that makes every .ogg path in the engine work. */
static ma_decoder_config vorbis_config(void) {
    static ma_decoding_backend_vtable *backends[] = { &rgame_vorbis_decoding_backend };

    ma_decoder_config config = ma_decoder_config_init_default();
    config.ppCustomBackendVTables = backends;
    config.customBackendCount = 1;
    return config;
}

/* Writes `bytes` to a scratch file and returns its path, for the malformed
 * cases. Static buffer: one at a time is all any test needs. */
static const char *scratch_file(const void *bytes, size_t length) {
    static char path[] = "/tmp/rgame_vorbis_testXXXXXX";
    strcpy(path, "/tmp/rgame_vorbis_testXXXXXX");

    int fd = mkstemp(path);
    ck_assert_int_ge(fd, 0);
    FILE *file = fdopen(fd, "wb");
    ck_assert_ptr_nonnull(file);
    if (length > 0) {
        ck_assert_uint_eq(fwrite(bytes, 1, length, file), length);
    }
    fclose(file);
    return path;
}

/* --- the working case --- */

START_TEST(an_ogg_opens_with_the_right_format) {
    ma_decoder_config config = vorbis_config();
    ma_decoder decoder;

    ck_assert_int_eq(ma_decoder_init_file(FIXTURE, &config, &decoder), MA_SUCCESS);

    ma_format format;
    ma_uint32 channels = 0, rate = 0;
    ck_assert_int_eq(ma_decoder_get_data_format(&decoder, &format, &channels, &rate, NULL, 0),
                     MA_SUCCESS);

    ck_assert_int_eq(channels, FIXTURE_CHANNELS);
    ck_assert_int_eq(rate, FIXTURE_RATE);

    ma_decoder_uninit(&decoder);
}
END_TEST

START_TEST(an_ogg_reports_its_length) {
    ma_decoder_config config = vorbis_config();
    ma_decoder decoder;
    ma_decoder_init_file(FIXTURE, &config, &decoder);

    ma_uint64 frames = 0;
    ck_assert_int_eq(ma_decoder_get_length_in_pcm_frames(&decoder, &frames), MA_SUCCESS);
    ck_assert_uint_eq(frames, FIXTURE_FRAMES);

    ma_decoder_uninit(&decoder);
}
END_TEST

START_TEST(reading_yields_pcm_and_then_reports_the_end) {
    ma_decoder_config config = vorbis_config();
    ma_decoder decoder;
    ma_decoder_init_file(FIXTURE, &config, &decoder);

    float buffer[1024 * FIXTURE_CHANNELS];
    ma_uint64 total = 0;
    ma_uint64 read = 0;

    /* Drain it. The loop is bounded well above the fixture's length so a
     * decoder that never reports the end fails rather than hangs. */
    ma_result result = MA_SUCCESS;
    for (int i = 0; i < 100; i++) {
        result = ma_decoder_read_pcm_frames(&decoder, buffer, 1024, &read);
        if (result != MA_SUCCESS) {
            break;
        }
        total += read;
    }

    ck_assert_uint_eq(total, FIXTURE_FRAMES);
    /* And it says so, rather than returning zero frames forever. A caller that
     * loops until the read fails would otherwise spin. */
    ck_assert_int_eq(result, MA_AT_END);

    ma_decoder_uninit(&decoder);
}
END_TEST

START_TEST(both_channels_carry_sound_and_they_differ) {
    /*
     * The reason the fixture is asymmetric. A decoder that reads one channel
     * and duplicates it, or muddles the interleaving, produces two identical
     * channels — which is exactly what a correct decode of a mono file looks
     * like, and would otherwise pass every other assertion here.
     */
    ma_decoder_config config = vorbis_config();
    ma_decoder decoder;
    ma_decoder_init_file(FIXTURE, &config, &decoder);

    float buffer[2048 * FIXTURE_CHANNELS];
    ma_uint64 read = 0;
    ma_decoder_read_pcm_frames(&decoder, buffer, 2048, &read);
    ck_assert_uint_gt(read, 1000);

    double left = 0.0, right = 0.0, difference = 0.0;
    for (ma_uint64 i = 0; i < read; i++) {
        float l = buffer[(i * 2)];
        float r = buffer[(i * 2) + 1];
        left += (double)l * l;
        right += (double)r * r;
        difference += (double)(l - r) * (l - r);
    }

    ck_assert_double_gt(left, 1.0);       /* not silence */
    ck_assert_double_gt(right, 1.0);      /* nor is the other one */
    ck_assert_double_gt(difference, 1.0); /* and they are not the same signal */

    ma_decoder_uninit(&decoder);
}
END_TEST

START_TEST(the_samples_really_are_floats) {
    /*
     * The data source declares its format as well as producing it, and the two
     * have to agree. Nothing catches a disagreement while the output format
     * matches the input, because miniaudio then converts nothing and the bytes
     * pass through whatever they are — so this decoder is asked for a *specific*
     * output format, which forces a conversion. Float samples mislabelled as
     * 16-bit integers come out of that conversion as garbage, and garbage is
     * not quiet: the range check is what sees it.
     */
    ma_decoder_config config = vorbis_config();
    config.format = ma_format_f32;
    config.channels = FIXTURE_CHANNELS;
    config.sampleRate = FIXTURE_RATE;

    ma_decoder decoder;
    ck_assert_int_eq(ma_decoder_init_file(FIXTURE, &config, &decoder), MA_SUCCESS);

    float buffer[1024 * FIXTURE_CHANNELS];
    ma_uint64 read = 0;
    ma_decoder_read_pcm_frames(&decoder, buffer, 1024, &read);
    ck_assert_uint_gt(read, 500);

    double peak = 0.0;
    for (ma_uint64 i = 0; i < read * FIXTURE_CHANNELS; i++) {
        double magnitude = buffer[i] < 0 ? -buffer[i] : buffer[i];
        if (magnitude > peak) {
            peak = magnitude;
        }
    }

    /* Audible, and inside the range a float sample is defined over. */
    ck_assert_double_gt(peak, 0.1);
    ck_assert_double_le(peak, 1.0);

    ma_decoder_uninit(&decoder);
}
END_TEST

START_TEST(seeking_back_to_the_start_replays_the_same_audio) {
    /* Looping music depends on this: at the end of a track the engine seeks to
     * zero and keeps reading. A seek that silently did nothing would leave a
     * loop playing silence after its first pass. */
    ma_decoder_config config = vorbis_config();
    ma_decoder decoder;
    ma_decoder_init_file(FIXTURE, &config, &decoder);

    float first[64 * FIXTURE_CHANNELS];
    float again[64 * FIXTURE_CHANNELS];
    ma_uint64 read = 0;

    ma_decoder_read_pcm_frames(&decoder, first, 64, &read);
    ck_assert_uint_eq(read, 64);

    /* Move somewhere else, then come back. */
    ma_decoder_read_pcm_frames(&decoder, again, 64, &read);
    ck_assert_int_eq(ma_decoder_seek_to_pcm_frame(&decoder, 0), MA_SUCCESS);
    ma_decoder_read_pcm_frames(&decoder, again, 64, &read);
    ck_assert_uint_eq(read, 64);

    for (int i = 0; i < 64 * FIXTURE_CHANNELS; i++) {
        ck_assert_float_eq_tol(again[i], first[i], 1e-4f);
    }

    ma_decoder_uninit(&decoder);
}
END_TEST

/* --- the callback path, which is the one the engine uses --- */

START_TEST(the_engine_can_read_an_ogg_too) {
    /*
     * The finding that cost the most to discover: `ma_decoder_init_file` uses
     * the backend's onInitFile, but ma_engine reads through miniaudio's own
     * virtual file system and calls onInit with read/seek/tell callbacks. A
     * backend with only onInitFile passes every test above and then fails
     * inside the engine with a bare MA_INVALID_FILE.
     *
     * The null backend is a device that consumes frames on a timer and produces
     * silence, so this runs with no sound card — here, and in CI.
     */
    ma_backend null_only[] = { ma_backend_null };
    ma_context_config context_config = ma_context_config_init();
    ma_context context;
    ck_assert_int_eq(ma_context_init(null_only, 1, &context_config, &context), MA_SUCCESS);

    static ma_decoding_backend_vtable *backends[] = { &rgame_vorbis_decoding_backend };
    ma_resource_manager_config manager_config = ma_resource_manager_config_init();
    manager_config.ppCustomDecodingBackendVTables = backends;
    manager_config.customDecodingBackendCount = 1;

    ma_resource_manager manager;
    ck_assert_int_eq(ma_resource_manager_init(&manager_config, &manager), MA_SUCCESS);

    ma_engine_config engine_config = ma_engine_config_init();
    engine_config.pContext = &context;
    engine_config.pResourceManager = &manager;

    ma_engine engine;
    ck_assert_int_eq(ma_engine_init(&engine_config, &engine), MA_SUCCESS);

    /* Decoded up front: the sound-effect case. */
    ck_assert_int_eq(ma_engine_play_sound(&engine, FIXTURE, NULL), MA_SUCCESS);

    /* Streamed: the music case, and a second code path through onInit. */
    ma_sound music;
    ck_assert_int_eq(
        ma_sound_init_from_file(&engine, FIXTURE, MA_SOUND_FLAG_STREAM, NULL, NULL, &music),
        MA_SUCCESS);
    ma_sound_uninit(&music);

    ma_engine_uninit(&engine);
    ma_resource_manager_uninit(&manager);
    ma_context_uninit(&context);
}
END_TEST

/* --- files that are not oggs --- */

START_TEST(the_engine_refuses_a_file_that_is_not_an_ogg) {
    /* The malformed cases above all go in through onInitFile. This one goes in
     * through onInit, which is a different function with its own reading and
     * its own allocation to get wrong — and it is the path the engine uses, so
     * it is the one a game would actually hit. */
    ma_backend null_only[] = { ma_backend_null };
    ma_context_config context_config = ma_context_config_init();
    ma_context context;
    ma_context_init(null_only, 1, &context_config, &context);

    static ma_decoding_backend_vtable *backends[] = { &rgame_vorbis_decoding_backend };
    ma_resource_manager_config manager_config = ma_resource_manager_config_init();
    manager_config.ppCustomDecodingBackendVTables = backends;
    manager_config.customDecodingBackendCount = 1;
    ma_resource_manager manager;
    ma_resource_manager_init(&manager_config, &manager);

    ma_engine_config engine_config = ma_engine_config_init();
    engine_config.pContext = &context;
    engine_config.pResourceManager = &manager;
    ma_engine engine;
    ma_engine_init(&engine_config, &engine);

    const char *text = "not an ogg";
    const char *garbage = scratch_file(text, strlen(text));
    ck_assert_int_ne(ma_engine_play_sound(&engine, garbage, NULL), MA_SUCCESS);
    remove(garbage);

    const char *empty = scratch_file("", 0);
    ck_assert_int_ne(ma_engine_play_sound(&engine, empty, NULL), MA_SUCCESS);
    remove(empty);

    ma_engine_uninit(&engine);
    ma_resource_manager_uninit(&manager);
    ma_context_uninit(&context);
}
END_TEST

START_TEST(a_missing_file_is_refused) {
    ma_decoder_config config = vorbis_config();
    ma_decoder decoder;

    ck_assert_int_ne(ma_decoder_init_file("/no/such/sound.ogg", &config, &decoder), MA_SUCCESS);
}
END_TEST

START_TEST(a_file_that_is_not_an_ogg_is_refused) {
    ma_decoder_config config = vorbis_config();
    ma_decoder decoder;

    const char *text = "this is not an ogg, it is a sentence";
    const char *path = scratch_file(text, strlen(text));

    ck_assert_int_ne(ma_decoder_init_file(path, &config, &decoder), MA_SUCCESS);
    remove(path);
}
END_TEST

START_TEST(an_empty_file_is_refused) {
    ma_decoder_config config = vorbis_config();
    ma_decoder decoder;
    const char *path = scratch_file("", 0);

    ck_assert_int_ne(ma_decoder_init_file(path, &config, &decoder), MA_SUCCESS);
    remove(path);
}
END_TEST

START_TEST(a_truncated_ogg_is_refused_or_decodes_what_is_there) {
    /*
     * A real ogg cut in half. Either answer is defensible — refuse it, or
     * decode the frames that survived — and which one stb gives is its
     * business. What must not happen is a crash or a read past the buffer,
     * which is what the sanitizer build is watching for here.
     */
    FILE *source = fopen(FIXTURE, "rb");
    ck_assert_ptr_nonnull(source);
    unsigned char bytes[4096];
    size_t got = fread(bytes, 1, sizeof(bytes), source);
    fclose(source);
    ck_assert_uint_gt(got, 100);

    const char *path = scratch_file(bytes, got / 2);

    ma_decoder_config config = vorbis_config();
    ma_decoder decoder;
    if (ma_decoder_init_file(path, &config, &decoder) == MA_SUCCESS) {
        float buffer[256 * FIXTURE_CHANNELS];
        ma_uint64 read = 0;
        for (int i = 0; i < 100; i++) {
            if (ma_decoder_read_pcm_frames(&decoder, buffer, 256, &read) != MA_SUCCESS) {
                break;
            }
        }
        ma_decoder_uninit(&decoder);
    }
    remove(path);
}
END_TEST

START_TEST(a_file_of_random_bytes_is_refused) {
    ma_decoder_config config = vorbis_config();
    ma_decoder decoder;

    /* Starts with the ogg magic so the format sniffing gets past the first
     * four bytes and has to reject it on the contents. */
    unsigned char bytes[512];
    memcpy(bytes, "OggS", 4);
    for (size_t i = 4; i < sizeof(bytes); i++) {
        bytes[i] = (unsigned char)((i * 37) & 0xFF);
    }
    const char *path = scratch_file(bytes, sizeof(bytes));

    ck_assert_int_ne(ma_decoder_init_file(path, &config, &decoder), MA_SUCCESS);
    remove(path);
}
END_TEST

START_TEST(opening_and_closing_repeatedly_leaks_nothing) {
    /* The compressed bytes read by the callback path outlive the call that read
     * them and are freed in uninit — the one place this backend owns memory.
     * Under the sanitizer, forgetting that shows up here. */
    for (int i = 0; i < 20; i++) {
        ma_decoder_config config = vorbis_config();
        ma_decoder decoder;
        ck_assert_int_eq(ma_decoder_init_file(FIXTURE, &config, &decoder), MA_SUCCESS);

        float buffer[128 * FIXTURE_CHANNELS];
        ma_uint64 read = 0;
        ma_decoder_read_pcm_frames(&decoder, buffer, 128, &read);
        ma_decoder_uninit(&decoder);
    }
}
END_TEST

Suite *vorbis_decoder_suite(void) {
    Suite *suite = suite_create("vorbis_decoder");
    TCase *tc = tcase_create("core");

    tcase_add_test(tc, an_ogg_opens_with_the_right_format);
    tcase_add_test(tc, an_ogg_reports_its_length);
    tcase_add_test(tc, reading_yields_pcm_and_then_reports_the_end);
    tcase_add_test(tc, both_channels_carry_sound_and_they_differ);
    tcase_add_test(tc, the_samples_really_are_floats);
    tcase_add_test(tc, seeking_back_to_the_start_replays_the_same_audio);

    tcase_add_test(tc, the_engine_can_read_an_ogg_too);
    tcase_add_test(tc, the_engine_refuses_a_file_that_is_not_an_ogg);

    tcase_add_test(tc, a_missing_file_is_refused);
    tcase_add_test(tc, a_file_that_is_not_an_ogg_is_refused);
    tcase_add_test(tc, an_empty_file_is_refused);
    tcase_add_test(tc, a_truncated_ogg_is_refused_or_decodes_what_is_there);
    tcase_add_test(tc, a_file_of_random_bytes_is_refused);
    tcase_add_test(tc, opening_and_closing_repeatedly_leaks_nothing);

    suite_add_tcase(suite, tc);
    return suite;
}
