# frozen_string_literal: true

require_relative 'version'
require_relative 'core/app'
require_relative 'core/input'
require_relative 'core/gamepad'
require_relative 'core/image'
require_relative 'core/renderer'
require_relative 'core/recording'
require_relative 'core/font'
require_relative 'core/audio'
require_relative 'core/sprite_sheet'
require_relative 'core/nine_slice'
require_relative 'core/ui_atlas'
require_relative 'core/tile_map_renderer'
require_relative 'core/asset_manager'
