# frozen_string_literal: true

# Engine core: pure Ruby, no Gosu. Safe to require in headless tests.
require_relative 'engine/matrix'
require_relative 'engine/tensor'
require_relative 'engine/signal'
require_relative 'engine/node2d'
require_relative 'engine/component'
require_relative 'engine/animation_set'
require_relative 'engine/animator'
require_relative 'engine/camera'
require_relative 'engine/camera_view'
require_relative 'engine/path'
require_relative 'engine/timer'
require_relative 'engine/tileset'
require_relative 'engine/tile_map'
require_relative 'engine/tile_collision'
require_relative 'engine/collision_box'
require_relative 'engine/collision_system'
require_relative 'engine/circle_collider'
require_relative 'engine/spatial_hash'
require_relative 'engine/pool'
require_relative 'engine/resettable'
require_relative 'engine/audio_bus'
require_relative 'engine/audio_director'
require_relative 'engine/i18n'
require_relative 'engine/cached_label'
require_relative 'engine/debug_overlay'
require_relative 'engine/body'
require_relative 'engine/actor'
require_relative 'engine/input/actions'
require_relative 'engine/input/action_mapper'
require_relative 'engine/input/player_controller'
# require_relative 'engine/ui/localized'
# require_relative 'engine/ui/control'
# require_relative 'engine/ui/button'
# require_relative 'engine/ui/panel'
# require_relative 'engine/ui/label'
# require_relative 'engine/ui/selector'
# require_relative 'engine/ui/menu'
require_relative 'engine/scene/scene_stack'
require_relative 'engine/components/velocity'
require_relative 'engine/components/pool'
require_relative 'engine/components/path_follow'
require_relative 'engine/components/timer'
require_relative 'engine/components/clickable'
require_relative 'engine/components/screen_wrap'
require_relative 'engine/components/despawn_offscreen'
require_relative 'engine/components/circle_collider'
require_relative 'engine/components/collision_world'
require_relative 'engine/components/targeting'
require_relative 'engine/components/sprite'
require_relative 'engine/components/thrust_controller'
require_relative 'engine/components/action_trigger'
require_relative 'engine/components/tile_world'
require_relative 'engine/components/character_body'
require_relative 'engine/components/player_controller'
require_relative 'engine/components/wander_controller'
require_relative 'engine/components/animated_sprite'
